INSERT INTO authors (name) VALUES
('J.K. Rowling'),
('George R. R. Martin'),
('J.R.R. Tolkien'),
('F. Scott Fitzgerald'),
('George Orwell'),
('Jane Austen'),
('Gabriel García Márquez'),
('Miguel de Cervantes'),
('Fyodor Dostoevsky'),
('Franz Kafka'),
('Juan Rulfo'),
('Ray Bradbury'),
('Aldous Huxley'),
('Albert Camus'),
('Stephen King'),
('William Peter Blatty'),
('Bram Stoker'),
('Oscar Wilde'),
('John Green'),
('Rainbow Rowell'),
('Harper Lee'),
('Alice Kellen'),
('Andrea Tomé'),
('Edgar Allan Poe'),
('Paula Hawkins'),
('James Ellroy'),
('Arthur Conan Doyle'),
('Ernesto Sábato'),
('Julio Cortázar'),
('Laura Esquivel'),
('Mario Benedetti'),
('Jorge Luis Borges'),
('Alejandra Pizarnik'),
('Gabriela Mistral'),
('Homero'),
('Emily Brontë'),
('Jonathan Swift'),
('Antoine de Saint-Exupéry');
